language: go
sudo: false
matrix:
  fast_finish: true
  include:
    - go: 1.14.x
      env: TEST_METHOD=goveralls
    - go: 1.13.x
    - go: 1.12.x
    - go: 1.11.x
    - go: 1.10.x
    - go: tip
    - go: 1.9.x
    - go: 1.8.x
    - go: 1.7.x
    - go: 1.6.x
    - go: 1.5.x
    - go: 1.14.x
      arch : ppc64le
      env: TEST_METHOD=goveralls
    - go: 1.13.x
      arch : ppc64le
    - go: 1.12.x
      arch : ppc64le
    - go: 1.11.x
      arch : ppc64le
    - go: 1.10.x
      arch : ppc64le
    - go: tip
      arch : ppc64le
    - go: 1.9.x
      arch : ppc64le
    - go: 1.8.x
      arch : ppc64le
    - go: 1.7.x
      arch : ppc64le
    - go: 1.6.x
      arch : ppc64le
    - go: 1.5.x
      arch : ppc64le

  allow_failures:
    - go: tip
    - go: 1.11.x
    - go: 1.10.x
    - go: 1.9.x
    - go: 1.8.x
    - go: 1.7.x
    - go: 1.6.x
    - go: 1.5.x
script: ./test.sh $TEST_METHOD
notifications:
  email:
    on_success: never
